sudo: true
dist: trusty
language: python
python:
  - "2.7"
before_install:
 - echo 'deb [arch=amd64] http://repo.powerdns.com/ubuntu trusty-auth-master main' | sudo tee -a /etc/apt/sources.list.d/powerdns.list
 - echo 'deb [arch=amd64] http://repo.powerdns.com/ubuntu trusty-dnsdist-master main' | sudo tee -a /etc/apt/sources.list.d/powerdns.list
 - echo 'deb [arch=amd64] http://repo.powerdns.com/ubuntu trusty-rec-master main' | sudo tee -a /etc/apt/sources.list.d/powerdns.list
 - curl https://repo.powerdns.com/CBC8B383-pub.asc | sudo apt-key add -
 - sudo apt-get -qq update
 - sudo apt-get install -y dnsdist pdns-recursor pdns-backend-mysql pdns-server
install:
 - "pip install -r requirements.txt"
before_script:
 - export DISPLAY=:99
 - ./.travis.task before_script
script:
 - ./manage.py assets build
 - ./.travis.task run_with_server -- node_modules/.bin/karma start test/karma.conf.js --no-auto-watch --single-run --reporters=dots --browsers=Firefox
 - ./.travis.task run_with_server -- node_modules/.bin/protractor test/protractor-conf.js --browser=firefox
notifications:
  irc:
    channels:
      - "irc.oftc.net#powerdns-dev"
    template:
      - "%{author} @ %{repository} / %{branch} - Build:#%{build_number} : %{message} - Changes: %{compare_url} - Build details: %{build_url}"
    use_notice: true
    skip_join: true
