#!/usr/bin/env python
# Jan-Piet Mens <jpmens(at)gmail.com>

import sys
import os
import requests
import json
import time
import socket
import urlparse

auth = [ 'udp-queries', 'udp-answers']
recursor = [    # http://doc.powerdns.com/recursor-stats.html
		"all-outqueries",
		"answers0-1",
		"answers100-1000",
		"answers10-100",
		"answers1-10",
		"answers-slow",
		"cache-bytes",
		"cache-entries",
		"cache-hits",
		"cache-misses",
		"chain-resends",
		"client-parse-errors",
		"concurrent-queries",
		"dlg-only-drops",
		"dont-outqueries",
		"ipv6-outqueries",
		"max-mthread-stack",
		"negcache-entries",
		"noerror-answers",
		"nsspeeds-entries",
		"nsset-invalidations",
		"nxdomain-answers",
		"outgoing-timeouts",
		"over-capacity-drops",
		"packetcache-bytes",
		"packetcache-entries",
		"packetcache-hits",
		"packetcache-misses",
		"qa-latency",
		"questions",
		"resource-limits",
		"server-parse-errors",
		"servfail-answers",
		"spoof-prevents",
		"sys-msec",
		"tcp-client-overflow",
		"tcp-outqueries",
		"tcp-questions",
		"throttled-out",
		"throttle-entries",
		"unauthorized-tcp",
		"unauthorized-udp",
		"unexpected-packets",
		"uptime",
		"user-msec"
   ]

CARBONSERVER = '127.0.0.1'
CARBONPORT = 2003
DELAY = 15  #seconds

def send_it(message):

    try:
        sock = socket.socket()
        sock.connect((CARBONSERVER, CARBONPORT))
        sock.sendall(message)
        sock.close()
    except socket.error:
        print "Can't connect to Carbon server at %s:%s" % (CARBONSERVER, CARBONPORT)
        sys.exit(1)
    except:
        pass

def nowtics():
    return int(time.time())

def getserverlist(serverlist_url):

    r = requests.get(serverlist_url)
    s = json.loads(r.text)
    return s

def graph_server(url, type, keys, node):

    print "--------- %-10s %-20s %s" % (type, node, url)
    node = node.replace('.', '-')

    r = requests.get(url)
    stats = json.loads(r.text)

    timestamp = nowtics()
    lines = []

    for s in statlist:
        if s in stats:
            lines.append("pdns.%s.%s.%s %s %d" % (node, type, s, stats[s], timestamp))

    message = '\n'.join(lines) + '\n'
    print message
    send_it(message)

if __name__ == '__main__':

    if len(sys.argv) < 2:
        sys.exit("Usage: %s serverlist.json [carbonserver port [interval]]" % sys.argv[0])

    serverlist_url = sys.argv[1]
    if len(sys.argv) >= 4:
        CARBONSERVER = sys.argv[2]
        CARBONPORT = int(sys.argv[3])

    if len(sys.argv) == 5:
        DELAY = int(sys.argv[4])

    while True:

        for server in getserverlist(serverlist_url)['servers']:
            url = server['url']
            if 'type' in server:
                url = urlparse.urljoin(url, 'stats')
                if server['type'] == 'Authoritative':
                    statlist = auth
                    type = 'auth'
                else:
                    statlist = recursor
                    type = 'recursor'
            graph_server(url, type, statlist, server['name'])
        time.sleep(DELAY)

